root: true
parser: '@typescript-eslint/parser'
plugins:
  - '@typescript-eslint/eslint-plugin'
  - prettier
  - import
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - react-app
  - react-app/jest
  - plugin:prettier/recommended
  - plugin:import/recommended
  - plugin:import/typescript
env:
  node: true
  jest: true
rules:
  '@typescript-eslint/interface-name-prefix': off
  '@typescript-eslint/explicit-function-return-type': off
  '@typescript-eslint/explicit-module-boundary-types': off
  '@typescript-eslint/no-explicit-any': off
  '@typescript-eslint/no-non-null-assertion': off
  '@typescript-eslint/no-unused-vars': error
  'jsx-a11y/no-redundant-roles': off
  # https://medium.com/weekly-webtips/how-to-sort-imports-like-a-pro-in-typescript-4ee8afd7258a
  'sort-imports':
    - off
    - ignoreCase: false
      ignoreDeclarationSort: true
      ignoreMemberSort: false
      memberSyntaxSortOrder:
        - none
        - all
        - multiple
        - single
      allowSeparatedGroups: false
  import/no-unresolved: error
  #import/order:
  #  - error
  #  - groups:
  #      - builtin
  #      - external
  #      - internal
  #      - parent
  #      - sibling
  #      - index
  #      - unknown
  #    newlines-between: always
  #    alphabetize:
  #      order: asc
  #      caseInsensitive: true
  jest/expect-expect:
    - error
    - assertFunctionNames: [expect, request.**.expect]
overrides:
  - files:
      - '**/*.stories.*'
    rules:
      import/no-anonymous-default-export: 'off'
