name: Test
on:
  push:
    branches:
      - '*'
  workflow_dispatch: null
jobs:
  test:
    name: run-tests
    runs-on: ubuntu-latest
    env:
      NODE_ENV: test
      REACT_APP_SUPABASE_ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ1Y3VxYnhvYmdwY2t6ZWxveHhzIiwicm9sZSI6ImFub24iLCJpYXQiOjE2NzAyODc1NTIsImV4cCI6MTk4NTg2MzU1Mn0.18UCG_SSSx1L0fU7dKoum7HIlof8kPVbj05pfyDJKdQ
      REACT_APP_SUPABASE_URL: https://bucuqbxobgpckzeloxxs.supabase.co
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
      - name: Install
        run: npm ci
      - name: Run Tests
        run: npm test
