name: Test
on:
  push:
    branches:
      - '*'
  workflow_dispatch: null
jobs:
  test:
    name: run-tests
    runs-on: ubuntu-latest
    env:
      NODE_ENV: test
      REACT_APP_SUPABASE_ANON_KEY: '${{ secrets.REACT_APP_SUPABASE_ANON_KEY }}'
      REACT_APP_SUPABASE_URL: '${{ secrets.REACT_APP_SUPABASE_URL }}'
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
      - name: Install
        run: npm ci
      - name: Run Tests
        run: npm test
